-- 🚀 MIGRACJA: Dodanie Karuzeli Hero i zdjęć "O mnie"
-- Uruchom ten skrypt w SQL Editorze w Supabase.

-- 1. Tworzy tabelę dla Karuzeli Hero (jeśli jeszcze nie istnieje)
CREATE TABLE IF NOT EXISTS hero_slides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image TEXT NOT NULL,
    seo_alt TEXT NOT NULL DEFAULT '',
    date TEXT NOT NULL DEFAULT '',
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2. Włącza zabezpieczenia RLS
ALTER TABLE hero_slides ENABLE ROW LEVEL SECURITY;

-- 3. Dodaje politykę dostępu (pozwala na wszystko — potem możesz to ograniczyć)
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'hero_slides' AND policyname = 'Allow all on hero_slides'
    ) THEN
        CREATE POLICY "Allow all on hero_slides" ON hero_slides FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;

-- 4. Dodaje nowe klucze do tabeli site_content dla zdjęć "O mnie"
-- (Używamy ON CONFLICT DO NOTHING, żeby nie nadpisać jeśli już ręcznie dodałeś)
INSERT INTO site_content (section, key, value) 
VALUES 
('about', 'about_image_1', '/05. Męski Azyl/Detal/DRP_174.jpg'),
('about', 'about_image_2', '/05. Męski Azyl/Detal/DRP_175.jpg'),
('about', 'about_image_3', '/05. Męski Azyl/Detal/DRP_176.jpg')
ON CONFLICT (section, key) DO NOTHING;

-- 5. Czyści tabelę slajdów i dodaje startowe dane (opcjonalnie — możesz to pominąć jeśli masz już własne slajdy)
-- DELETE FROM hero_slides;
INSERT INTO hero_slides (image, seo_alt, date, sort_order) 
VALUES
('/05. Męski Azyl/DRP_42.jpg', 'Nowoczesny męski azyl w Kaliszu - Projektowanie Wnętrz Joanna Tomaska', '''24', 1),
('/06. Spokojna przestrzeń/DRP_65.jpg', 'Spokojna przestrzeń - Architektura Wnętrz Kalisz i okolice by Tomaska Studio', '''24', 2),
('/07. Przytulne wnętrze/20240620_211601.jpg', 'Przytulne wnętrze domu pod Kaliszem - Aranżacja i Projektowanie Wnętrz Joanna Tomaska', '''23', 3),
('/08. Nowoczesna forma/1_4.jpg', 'Nowoczesna forma apartamentu w Kaliszu - Ekskluzywne Wnętrza Architekt Joanna Tomaska', '''23', 4)
ON CONFLICT DO NOTHING;
