-- Tomaska Studio CMS — Database Schema
-- Run this in Supabase SQL Editor (Dashboard → SQL Editor → New query)

-- 1. Site Content (key-value per section)
CREATE TABLE IF NOT EXISTS site_content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section TEXT NOT NULL,
    key TEXT NOT NULL,
    value TEXT NOT NULL DEFAULT '',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(section, key)
);

-- 2. Projects
CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    year TEXT NOT NULL DEFAULT '',
    image TEXT NOT NULL DEFAULT '',
    seo_alt TEXT NOT NULL DEFAULT '',
    gallery JSONB NOT NULL DEFAULT '[]'::jsonb,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 3. Testimonials
CREATE TABLE IF NOT EXISTS testimonials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    project TEXT NOT NULL DEFAULT '',
    quote TEXT NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 4. Offer Steps
CREATE TABLE IF NOT EXISTS offer_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    step_number TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable RLS (but allow all for now — auth comes later)
ALTER TABLE site_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE offer_steps ENABLE ROW LEVEL SECURITY;

-- Temporary open policies (replace with auth policies later)
CREATE POLICY "Allow all on site_content" ON site_content FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on projects" ON projects FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on testimonials" ON testimonials FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on offer_steps" ON offer_steps FOR ALL USING (true) WITH CHECK (true);

-- SEED DATA: Site Content
INSERT INTO site_content (section, key, value) VALUES
('hero', 'quote', '„Tworzę przestrzeń idealną dla klienta, poznając jego osobowość oraz indywidualne potrzeby."'),
('about', 'paragraph_1', 'Jako absolwentka wrocławskiej ASP i założycielka TOMASKA STUDIO, patrzę na architekturę dwutorowo. Fascynują mnie wnętrza budynków, ale kluczem do ich zrozumienia są dla mnie wnętrza ludzi, którzy w nich mieszkają.'),
('about', 'paragraph_2', 'Wierzę, że przestrzeń ma realny wpływ na nasze życie. Dlatego każdy projekt zaczynam od poznania Twoich potrzeb, pasji i stylu bycia. Nie narzucam wizji – łączę Twoje oczekiwania z moim doświadczeniem.'),
('about', 'paragraph_3', 'Tworzę projekty ponadczasowe. Łączę fakturę, kolor i światło z funkcjonalnością. Efekt? Wnętrze, które jest nie tylko inspirujące i piękne, ale przede wszystkim wygodne. To ma być Twój azyl.'),
('contact', 'designer_name', 'Joanna Tomaska'),
('contact', 'phone', '885 469 189'),
('contact', 'email', 'wnetrza@tomaskastudio.pl'),
('contact', 'heading', 'Zostańmy w kontakcie!'),
('contact', 'description', 'Jesteś zainteresowany projektem wnętrza lub chciałbyś dowiedzieć się jak wygląda współpraca z projektantem? Pisz lub dzwoń śmiało! Odpowiem na wszystkie Twoje pytania.')
ON CONFLICT (section, key) DO NOTHING;

-- SEED DATA: Projects
INSERT INTO projects (title, category, description, year, image, seo_alt, gallery, sort_order) VALUES
('Elegancja marmuru', '01', 'Projekt wnętrza apartamentu w centrum Warszawy, gdzie główną rolę gra szlachetny marmur Calacatta Oro. Przestrzeń została zaprojektowana z myślą o płynnym przenikaniu się stref funkcjonalnych, tworząc spójną, elegancką całość. Zastosowanie naturalnych materiałów – kamienia, drewna dębowego i lnu – nadaje wnętrzu ciepła, mimo jego luksusowego charakteru. Każdy detal, od frezowania frontów po dobór sztukaterii, był starannie przemyślany, aby podkreślić ponadczasowy styl.', '2024', 'http://tomaskastudio.pl/wp-content/uploads/2020/04/n2.jpg', 'Elegancja marmuru Calacatta Oro - Luksusowy Apartament Kalisz Projektant Wnętrz', '["http://tomaskastudio.pl/wp-content/uploads/2020/05/Wn%C4%99trze-salon-scaled.jpg","http://tomaskastudio.pl/wp-content/uploads/2020/04/2-1.jpg","http://tomaskastudio.pl/wp-content/uploads/2020/04/8a.jpg","http://tomaskastudio.pl/wp-content/uploads/2020/04/4.jpg","http://tomaskastudio.pl/wp-content/uploads/2022/02/70fb63ad-5a2d-408c-87ae-7e6c00f090b4.jpg"]', 1),
('Mocniejszy akcent', '02', 'Odważna realizacja dla młodego inwestora, który nie bał się ciemnych barw i surowych faktur. Grafit, głęboki granat i czerń zostały przełamane ciepłym oświetleniem i miedzianymi dodatkami. Wnętrze ma charakter loftowy, ale z nutą elegancji. Otwarta przestrzeń dzienna łączy się z aneksem kuchennym, tworząc idealne miejsce do spotkań towarzyskich. Sypialnia, utrzymana w ciemnej tonacji, sprzyja wyciszeniu i regeneracji.', '2023', 'http://tomaskastudio.pl/wp-content/uploads/2022/02/bd1cf092-14a9-4f67-9e1d-5da16b65b7c8.jpg', 'Mocniejszy akcent loftowy - Nowoczesna Architektura Wnętrz i Aranżacja Joanna Tomaska', '["http://tomaskastudio.pl/wp-content/uploads/2022/02/4130333f-abf1-4255-9f6c-89b60624ef7c.jpg","http://tomaskastudio.pl/wp-content/uploads/2022/02/c724fa57-df12-4135-9799-01117666bf5e.jpg","http://tomaskastudio.pl/wp-content/uploads/2022/02/15e5f088-12c0-4a3f-86e1-5fb88314a4bd.jpg","http://tomaskastudio.pl/wp-content/uploads/2022/02/3d16d835-b7da-41ff-aac5-b844cb2fd37d.jpg","http://tomaskastudio.pl/wp-content/uploads/2022/02/6372ba35-b897-4009-a552-f55ee42dbb70.jpg"]', 2),
('Nowoczesna klasyka', '03', 'Harmonijne połączenie klasycznych form ze współczesnym designem. Projekt domu pod Krakowem, w którym liczył się spokój i równowaga. Jasna paleta barw – beże, biele i szarości – stanowi tło dla starannie dobranych mebli i dzieł sztuki. Sztukaterie na ścianach nawiązują do tradycji, podczas gdy nowoczesne oświetlenie i proste formy mebli nadają wnętrzu świeżości. To przestrzeń, która "oddycha" i daje poczucie luksusowego komfortu.', '2023', 'http://tomaskastudio.pl/wp-content/uploads/2022/02/161ac075-fecf-4530-ac96-e9ab78fd5d70.jpg', 'Nowoczesna klasyka w domu pod Kaliszem - Jasne Wnętrza i Projektowanie Architekt Joanna Tomaska', '["http://tomaskastudio.pl/wp-content/uploads/2022/02/344a6e23-c3e7-4807-86f8-8c37d9105755.jpg","http://tomaskastudio.pl/wp-content/uploads/2022/02/16899579-655e-420b-803f-9c0eb7cb6fc1.jpg","http://tomaskastudio.pl/wp-content/uploads/2022/02/5881c6c0-903c-4971-8ffd-ef9e930b6aef.jpg","http://tomaskastudio.pl/wp-content/uploads/2022/02/28ed9b50-706e-4bbe-b69f-f454561518af.jpg","http://tomaskastudio.pl/wp-content/uploads/2022/02/61758a7d-2cac-4973-974c-9d940358449f.jpg"]', 3),
('Projekty Publiczne', '04', 'Rewitalizacja zabytkowej kamienicy na potrzeby butikowego hotelu. Wyzwanie polegało na zachowaniu historycznej tkanki budynku przy jednoczesnym wprowadzeniu nowoczesnych udogodnień. Lobby hotelowe zachwyca odrestaurowaną posadzką i oryginalnymi kolumnami, które zestawiono z miękkimi welurowymi sofami i nowoczesną recepcją. Każdy pokój ma indywidualny charakter, nawiązujący do historii miejsca, ale oferujący najwyższy standard wypoczynku.', '2022', 'http://tomaskastudio.pl/wp-content/uploads/2020/02/14-1.jpg', 'Projekty Publiczne - Rewitalizacja kamienicy Kalisz Architektura Wnętrz', '["http://tomaskastudio.pl/wp-content/uploads/2020/02/15.jpg","http://tomaskastudio.pl/wp-content/uploads/2020/02/13-a.jpg","http://tomaskastudio.pl/wp-content/uploads/2020/02/11.jpg","http://tomaskastudio.pl/wp-content/uploads/2020/02/7-ok.jpg","http://tomaskastudio.pl/wp-content/uploads/2022/02/39779e45-4413-44d5-aa2d-f9c56a99162a.jpg"]', 4),
('Męski azyl', '05', 'Męski, zdecydowany charakter tego wnętrza podkreślają mocne kontrasty i strukturalne tynki. Projekt, który łączy funkcjonalność z surowym, ale wyrafinowanym pięknem. Beton architektoniczny na ścianach, czarne, matowe detale i wyeksponowane elementy ze szczotkowanej stali tworzą tło dla skórzanych mebli wypoczynkowych. Kuchnia w formie monolitycznej wyspy staje się centralnym punktem apartamentu, idealnym dla pasjonata gotowania.', '2024', '/05. Męski Azyl/DRP.jpg', 'Męski azyl odecydowanym charakterze - Surowe Betonowe Wykończenie Architektura Wnętrz', '["/05. Męski Azyl/DRP_2.jpg","/05. Męski Azyl/DRP_15.jpg","/05. Męski Azyl/DRP_23.jpg","/05. Męski Azyl/DRP_27.jpg","/05. Męski Azyl/DRP_36.jpg"]', 5),
('Spokojna Przestrzeń', '06', 'Wnętrze utrzymane w stonowanej, jasnej palecie barw. Naturalne materiały i minimalistyczne formy tworzą przestrzeń sprzyjającą wyciszeniu i regeneracji. Projekt łączy funkcjonalność z estetyką, oferując harmonijne otoczenie do codziennego życia.', '2024', '/06. Spokojna przestrzeń/DRP_7.jpg', 'Spokojna przestrzeń - Projekt Wnętrza Jasne Wykończenie Architekt Kalisz', '["/06. Spokojna przestrzeń/DRP_32.jpg","/06. Spokojna przestrzeń/DRP_36.jpg","/06. Spokojna przestrzeń/DRP_38.jpg","/06. Spokojna przestrzeń/DRP_42.jpg","/06. Spokojna przestrzeń/DRP_58.jpg"]', 6),
('Przytulne Wnętrze', '07', 'Ciepłe, domowe wnętrze, w którym każdy detal służy budowaniu przytulnej atmosfery. Miękkie tkaniny, naturalne drewno i starannie dobrane oświetlenie tworzą przestrzeń, w której chce się spędzać czas. Projekt odzwierciedla indywidualny charakter mieszkańców.', '2023', '/07. Przytulne wnętrze/20240620_190101.jpg', 'Przytulne domowe wnętrze z drewnem okolic Kalisza - Projekt Wnętrza Joanna Tomaska', '["/07. Przytulne wnętrze/20240620_210734.jpg","/07. Przytulne wnętrze/20240620_211601.jpg","/07. Przytulne wnętrze/20240620_212234.jpg","/07. Przytulne wnętrze/20240620_212243.jpg","/07. Przytulne wnętrze/20240620_212257.jpg"]', 7),
('Nowoczesna Forma', '08', 'Projekt łączący nowoczesne formy architektoniczne z funkcjonalnym podejściem do przestrzeni. Czyste linie, geometryczne akcenty i przemyślana kompozycja materiałów tworzą wnętrze o silnym, współczesnym charakterze. Każde pomieszczenie to spójna wizja estetyczna.', '2023', '/08. Nowoczesna forma/1_3.jpg', 'Nowoczesna Forma Architektoniczna - Projekt Wnętrz w Okolicach Kalisza', '["/08. Nowoczesna forma/1_4.jpg","/08. Nowoczesna forma/1_9a.jpg","/08. Nowoczesna forma/1_10a.jpg","/08. Nowoczesna forma/1_15.jpg","/08. Nowoczesna forma/Przedsionek 1_10b.jpg","/08. Nowoczesna forma/Tv wall_1b.jpg"]', 8);

-- SEED DATA: Testimonials
INSERT INTO testimonials (name, project, quote, sort_order) VALUES
('Anna i Marek K.', 'Elegancja marmuru', 'Współpraca z Joanną to czysta przyjemność. Od pierwszego spotkania czuliśmy, że rozumie naszą wizję. Efekt przeszedł nasze najśmielsze oczekiwania — każdy detal jest przemyślany, a wnętrze żyje własnym życiem.', 1),
('Tomasz W.', 'Męski azyl', 'Szukałem projektantki, która nie boi się odważnych rozwiązań. Joanna zaproponowała beton architektoniczny i matowe detale, o których sam bym nie pomyślał. Mieszkanie wygląda jak z magazynu wnętrzarskiego, a jednocześnie jest niezwykle funkcjonalne.', 2),
('Katarzyna i Piotr D.', 'Nowoczesna klasyka', 'Nasz dom pod Krakowem zyskał duszę dzięki Joannie. Połączenie klasycznych sztukaterii z nowoczesnym oświetleniem to strzał w dziesiątkę. Goście zawsze pytają, kto projektował wnętrze!', 3),
('Magdalena S.', 'Spokojna przestrzeń', 'Po całym dniu w pracy potrzebuję wyciszenia. Joanna stworzyła przestrzeń, która jest jak azyl — jasna, spokojna, pełna naturalnych materiałów. Każdego dnia cieszę się, wracając do domu.', 4),
('Robert i Ewa N.', 'Przytulne wnętrze', 'Joanna potrafiła uchwycić charakter naszej rodziny i przełożyć go na projekt. Wnętrze jest ciepłe, domowe i idealnie dopasowane do naszych potrzeb. Dzieci uwielbiają swoje pokoje!', 5);

-- SEED DATA: Offer Steps
INSERT INTO offer_steps (step_number, title, description) VALUES
('01', 'Przygotowanie do procesu', 'Spotkanie – szczegółowe omówienie inspiracji oraz potrzeb funkcjonalnych i estetycznych. Pomiar – jeśli klient nie posiada rzutu.'),
('02', 'Układ Funkcjonalny', 'Możliwe opcje układów z wymiarowaniem na rzucie. Czarno-białe widoki 3D. Rozwiązania materiałowe w formie inspiracji. Korekty oraz wybór jednej wersji układu.'),
('03', 'Koncepcja Projektowa', 'Wizualizacje pokazujące kolorystykę i rozwiązania materiałowe we wnętrzu. Korekty oraz akceptacja rozwiązań.'),
('04', 'Dobór Materiałów i Rysunki Techniczne', 'Spotkanie w sklepach branżowych w celu wyboru materiałów wykończeniowych i wyposażenia. Projekt wodno-kanalizacyjny, elektryki, mebli na wymiar, rysunki zaprojektowanych ścian oraz zestawienie materiałów.');
